' UC2 - conversaciones con Inteligencia artificial
rectangle "Chat" {
  usecase "Enviar mensaje"                      as UC2_1
  usecase "Cambiar título de conversación"      as UC2_2
  usecase "Cambiar de conversación"             as UC2_3
  usecase "Agregar tarjeta desde conversación"  as UC2_4
}

Usuario --> UC2_1
Usuario --> UC2_2
Usuario --> UC2_3
Usuario --> UC2_4