' UC3 - Estudio
rectangle "Estudio" {
  usecase "Gestionar tarjetas"  as UC3_1
  usecase "Gestionar mazos"     as UC3_2
  usecase "Estudiar mazo"       as UC3_3
}

UC3_1 .. OptionalImage_Note

Usuario --> UC3_1
Usuario --> UC3_2
Usuario --> UC3_3