' UC5 - Productos
rectangle "Productos" {
  usecase "Asignar producto"      as UC5_1
  usecase "Gestionar visibilidad" as UC5_2
}

UC5_2 .. Razon_Note

Autor         --> UC5_1
Autor         --> UC5_2
Administrador --> UC5_2